import re
import sys

files = {
    'src/App.vue': [
        ('加载中...', 'Loading...'),
        ('IPA管理工具', 'IPA Management Tool'),
        ("'切换到浅色模式'", "'Switch to Light Mode'"),
        ("'切换到深色模式'", "'Switch to Dark Mode'"),
        ('title="退出登录"', 'title="Log Out"'),
        ('title="查看源代码"', 'title="View Source Code"'),
        ("ElMessage.success('已退出登录')", "ElMessage.success('Logged out')"),
    ],
    'src/components/Login.vue': [
        ('管理员登录', 'Admin Login'),
        ('默认账号：admin / admin', 'Default credentials: admin / admin'),
        ('label="用户名"', 'label="Username"'),
        ('label="密码"', 'label="Password"'),
        ('placeholder="请输入用户名"', 'placeholder="Please enter username"'),
        ('placeholder="请输入密码"', 'placeholder="Please enter password"'),
        ('>\\n            登录\\n          <', '>\\n            Sign In\\n          <'),
        ("title=\"检测到仍在使用默认密码，必须先修改密码后才能进入系统\"", "title=\"Default password detected, you must change your password before continuing\""),
        ("title='首次登录：请修改用户名和密码'", "title='First Login: Please update your username and password'"),
        ("title=\"首次登录：请修改用户名和密码\"", "title=\"First Login: Please update your username and password\""),
        ('label="新用户名"', 'label="New Username"'),
        ('label="当前密码"', 'label="Current Password"'),
        ('label="新密码"', 'label="New Password"'),
        ('label="确认新密码"', 'label="Confirm New Password"'),
        ('placeholder="请输入新用户名"', 'placeholder="Please enter new username"'),
        ('placeholder="请输入当前密码"', 'placeholder="Please enter current password"'),
        ('placeholder="请输入新密码"', 'placeholder="Please enter new password"'),
        ('placeholder="请再次输入新密码"', 'placeholder="Please confirm new password"'),
        ("message: '请输入用户名'", "message: 'Please enter username'"),
        ("message: '请输入密码'", "message: 'Please enter password'"),
        ("message: '请输入当前密码'", "message: 'Please enter current password'"),
        ("message: '请输入新密码'", "message: 'Please enter new password'"),
        ("message: '请确认新密码'", "message: 'Please confirm new password'"),
        ("callback(new Error('两次输入的新密码不一致'))", "callback(new Error('New passwords do not match'))"),
        (">\\n          修改密码\\n        <", ">\\n          Change Password\\n        <"),
        ("ElMessage.success('登录成功')", "ElMessage.success('Login successful')"),
        ("ElMessage.error(e?.message || '登录失败')", "ElMessage.error(e?.message || 'Login failed')"),
        ("let msg = '修改密码失败'", "let msg = 'Failed to change password'"),
        ("ElMessage.success('密码修改成功，请使用新密码重新登录')", "ElMessage.success('Password changed successfully, please log in with your new password')"),
        ("ElMessage.error(e?.message || '修改密码失败')", "ElMessage.error(e?.message || 'Failed to change password')"),
    ],
    'src/components/TabLayout.vue': [
        ("label: '下载'", "label: 'Download'"),
        ("label: '队列'", "label: 'Queue'"),
        ("label: '订阅'", "label: 'Subscriptions'"),
        ("label: '设置'", "label: 'Settings'"),
    ],
    'src/components/AppSubscription.vue': [
        ('应用订阅与更新', 'App Subscriptions & Updates'),
        ('个订阅 | ', ' subscriptions | '),
        ('个更新', ' updates'),
        ('>\\n          检查更新\\n        <', '>\\n          Check for Updates\\n        <'),
        ('>\\n          添加订阅\\n        <', '>\\n          Add Subscription\\n        <'),
        ('<!-- 更新通知 -->', '<!-- Update Notifications -->'),
        ('>\\n          发现更新\\n        <', '>\\n          Updates Found\\n        <'),
        ('>\\n                下载新版本\\n              <', '>\\n                Download New Version\\n              <'),
        ('<!-- 订阅列表 -->', '<!-- Subscription List -->'),
        ('>\\n          我的订阅\\n        <', '>\\n          My Subscriptions\\n        <'),
        ("{{ sub.artist_name || '未知开发者' }}", "{{ sub.artist_name || 'Unknown Developer' }}"),
        ("<span v-if=\"sub.current_version\">版本: {{ sub.current_version }}</span>", "<span v-if=\"sub.current_version\">Version: {{ sub.current_version }}</span>"),
        ('检查于: ', 'Checked: '),
        ('<!-- 空状态 -->', '<!-- Empty State -->'),
        ('>\\n        暂无订阅\\n      <', '>\\n        No subscriptions\\n      <'),
        ('添加应用订阅，及时获取更新通知', 'Add app subscriptions to receive update notifications'),
        ('<!-- 添加订阅对话框 -->', '<!-- Add Subscription Dialog -->'),
        ("title=\"添加订阅\"", "title=\"Add Subscription\""),
        ('label="应用ID"', 'label="App ID"'),
        ('placeholder="输入应用的 Bundle ID 或 Track ID"', 'placeholder="Enter the app\'s Bundle ID or Track ID"'),
        ('label="应用名称"', 'label="App Name"'),
        ('placeholder="输入应用名称"', 'placeholder="Enter app name"'),
        ('label="账号邮箱"', 'label="Account Email"'),
        ('placeholder="输入用于下载的账号邮箱"', 'placeholder="Enter the account email used for downloading"'),
        ('label="区域"', 'label="Region"'),
        ('placeholder="选择区域"', 'placeholder="Select region"'),
        ('label="美国"', 'label="United States"'),
        ('label="中国"', 'label="China"'),
        ('label="日本"', 'label="Japan"'),
        ('label="英国"', 'label="United Kingdom"'),
        ('label="德国"', 'label="Germany"'),
        ('>\\n          取消\\n        <', '>\\n          Cancel\\n        <'),
        ('>\\n          添加\\n        <', '>\\n          Add\\n        <'),
        ('// 加载订阅列表', '// Load subscription list'),
        ("ElMessage.error('加载订阅失败')", "ElMessage.error('Failed to load subscriptions')"),
        ('// 检查更新', '// Check for updates'),
        ("ElMessage.success(`发现 ${updates.value.length} 个更新`)", "ElMessage.success(`Found ${updates.value.length} update(s)`)"),
        ('// 逐个发送浏览器通知', '// Send browser notifications one by one'),
        ("ElMessage.info('所有应用都是最新版本')", "ElMessage.info('All apps are up to date')"),
        ("ElMessage.error(data.error || '检查更新失败')", "ElMessage.error(data.error || 'Failed to check for updates')"),
        ("ElMessage.error('检查更新失败')", "ElMessage.error('Failed to check for updates')"),
        ('// 添加订阅', '// Add subscription'),
        ("ElMessage.warning('请填写完整信息')", "ElMessage.warning('Please fill in all required fields')"),
        ("ElMessage.success('订阅添加成功')", "ElMessage.success('Subscription added successfully')"),
        ("ElMessage.error(data.error || '添加订阅失败')", "ElMessage.error(data.error || 'Failed to add subscription')"),
        ("ElMessage.error('添加订阅失败')", "ElMessage.error('Failed to add subscription')"),
        ('// 移除订阅', '// Remove subscription'),
        ("await ElMessageBox.confirm(`确定要取消订阅 \"${sub.app_name}\" 吗？`, '确认取消', {", "await ElMessageBox.confirm(`Are you sure you want to unsubscribe from \"${sub.app_name}\"?`, 'Confirm Unsubscribe', {"),
        ("ElMessage.success('取消订阅成功')", "ElMessage.success('Unsubscribed successfully')"),
        ("ElMessage.error(data.error || '取消订阅失败')", "ElMessage.error(data.error || 'Failed to unsubscribe')"),
        ("ElMessage.error('取消订阅失败')", "ElMessage.error('Failed to unsubscribe')"),
        ('// 下载更新', '// Download update'),
        ("ElMessage.info(`开始下载 ${update.app_name} 的更新...`)", "ElMessage.info(`Starting download of update for ${update.app_name}...`)"),
        ('// 这里可以触发下载逻辑', '// Download logic can be triggered here'),
        ('// 格式化日期', '// Format date'),
        ("return date.toLocaleString('zh-CN')", "return date.toLocaleString()"),
        ('// 自动检查更新', '// Auto-check for updates'),
    ],
    'src/components/BatchDownload.vue': [
        ('批量下载', 'Batch Download'),
        ('个批量任务', ' batch tasks'),
        ('>\\n          创建批量下载\\n        <', '>\\n          Create Batch Download\\n        <'),
        ('>\\n          刷新\\n        <', '>\\n          Refresh\\n        <'),
        ('<!-- 批量任务列表 -->', '<!-- Batch Task List -->'),
        ("task.status === 'completed' ? '已完成' : task.status === 'failed' ? '失败' : '进行中'", "task.status === 'completed' ? 'Completed' : task.status === 'failed' ? 'Failed' : 'In Progress'"),
        ('总数: ', 'Total: '),
        ('完成: ', 'Completed: '),
        ('失败: ', 'Failed: '),
        ('>\\n                  查看详情\\n                <', '>\\n                  View Details\\n                <'),
        ('>\\n                  删除\\n                <', '>\\n                  Delete\\n                <'),
        ('<!-- 空状态 -->', '<!-- Empty State -->'),
        ('>\\n        暂无批量下载任务\\n      <', '>\\n        No batch download tasks\\n      <'),
        ('点击"创建批量下载"开始批量下载应用', 'Click "Create Batch Download" to start downloading apps in bulk'),
        ('<!-- 创建批量下载对话框 -->', '<!-- Create Batch Download Dialog -->'),
        ("title=\"创建批量下载\"", "title=\"Create Batch Download\""),
        ('label="任务名称"', 'label="Task Name"'),
        ('placeholder="输入任务名称"', 'placeholder="Enter task name"'),
        ('label="应用列表"', 'label="App List"'),
        ('在下载页选择账号、APPID 和版本后，点击"添加到批量下载"', 'Select an account, App ID and version on the Download page, then click "Add to Batch Download"'),
        ('账号: ', 'Account: '),
        ('版本: ', 'Version: '),
        ("item.version_label || item.version || '最新版本'", "item.version_label || item.version || 'Latest Version'"),
        ('>\\n              移除\\n            <', '>\\n              Remove\\n            <'),
        ('>\\n              清空草稿\\n            <', '>\\n              Clear Drafts\\n            <'),
        ('还没有批量下载草稿项', 'No batch download draft items yet'),
        ('>\\n          取消\\n        <', '>\\n          Cancel\\n        <'),
        ('>\\n          创建\\n        <', '>\\n          Create\\n        <'),
        ('<!-- 任务详情对话框 -->', '<!-- Task Details Dialog -->'),
        ("title=\"批量下载详情\"", "title=\"Batch Download Details\""),
        ('>\\n            下载项目\\n          <', '>\\n            Download Items\\n          <'),
        ("版本: {{ item.version || '未知' }} | 账号: {{ item.account_email }}", "Version: {{ item.version || 'Unknown' }} | Account: {{ item.account_email }}"),
        ("item.status === 'completed' ? '已完成' : item.status === 'failed' ? '失败' : '进行中'", "item.status === 'completed' ? 'Completed' : item.status === 'failed' ? 'Failed' : 'In Progress'"),
        ('>\\n          关闭\\n        <', '>\\n          Close\\n        <'),
        ('// 加载批量任务', '// Load batch tasks'),
        ("ElMessage.error('加载批量任务失败')", "ElMessage.error('Failed to load batch tasks')"),
        ('// 创建批量任务', '// Create batch task'),
        ("ElMessage.warning('请输入任务名称')", "ElMessage.warning('Please enter a task name')"),
        ("ElMessage.warning('请先从下载页添加至少一个批量下载项')", "ElMessage.warning('Please add at least one item from the Download page first')"),
        ("ElMessage.success('批量任务创建成功')", "ElMessage.success('Batch task created successfully')"),
        ("ElMessage.error(data.error || '创建批量任务失败')", "ElMessage.error(data.error || 'Failed to create batch task')"),
        ("ElMessage.error('创建批量任务失败')", "ElMessage.error('Failed to create batch task')"),
        ('// 查看任务详情', '// View task details'),
        ("ElMessage.error('加载任务详情失败')", "ElMessage.error('Failed to load task details')"),
        ('// 删除任务', '// Delete task'),
        ("await ElMessageBox.confirm('确定要删除这个批量任务吗？', '确认删除', {", "await ElMessageBox.confirm('Are you sure you want to delete this batch task?', 'Confirm Delete', {"),
        ("ElMessage.success('删除成功')", "ElMessage.success('Deleted successfully')"),
        ("ElMessage.error(data.error || '删除失败')", "ElMessage.error(data.error || 'Delete failed')"),
        ("ElMessage.error('删除失败')", "ElMessage.error('Delete failed')"),
        ('// 计算进度', '// Calculate progress'),
        ('// 格式化日期', '// Format date'),
        ("return date.toLocaleString('zh-CN')", "return date.toLocaleString()"),
    ],
    'src/components/DownloadQueue.vue': [
        ('下载队列', 'Download Queue'),
        ('个当前任务 · ', ' active tasks · '),
        ('条记录 · 已占用 ', ' records · Storage used: '),
        ('>刷新<', '>Refresh<'),
        ('>清理服务器文件<', '>Clean Server Files<'),
        ('当前任务', 'Active Tasks'),
        ("{{ task.artistName || '未知开发者' }}", "{{ task.artistName || 'Unknown Developer' }}"),
        ('版本 {{ task.version || ', "Version {{ task.version || '"),
        ("|| '未知' }}", "|| 'Unknown' }}"),
        ("账号 {{ task.accountEmail || task.account?.email || '未知账号' }}", "Account {{ task.accountEmail || task.account?.email || 'Unknown Account' }}"),
        ("<span v-if=\"task.fileSize\">大小 {{ formatFileSize(task.fileSize) }}</span>", "<span v-if=\"task.fileSize\">Size {{ formatFileSize(task.fileSize) }}</span>"),
        ("<span v-if=\"task.progress !== undefined\">进度 {{ task.progress }}%</span>", "<span v-if=\"task.progress !== undefined\">Progress {{ task.progress }}%</span>"),
        ("<span v-if=\"task.stage\">阶段 {{ task.stage }}</span>", "<span v-if=\"task.stage\">Stage {{ task.stage }}</span>"),
        (">下载<", ">Download<"),
        (">安装<", ">Install<"),
        ("仅下载", "Download Only"),
        ("{{ task.status === 'completed' || task.status === 'failed' ? '移除' : '取消' }}", "{{ task.status === 'completed' || task.status === 'failed' ? 'Remove' : 'Cancel' }}"),
        ('下载记录', 'Download History'),
        ('>清空记录<', '>Clear History<'),
        ("{{ record.appName || '未命名 IPA' }}", "{{ record.appName || 'Unnamed IPA' }}"),
        ("{{ record.artistName || '未知开发者' }}", "{{ record.artistName || 'Unknown Developer' }}"),
        ("账号 {{ record.accountEmail || '未知账号' }}", "Account {{ record.accountEmail || 'Unknown Account' }}"),
        ("<span v-if=\"record.fileSize\">大小 {{ formatFileSize(record.fileSize) }}</span>", "<span v-if=\"record.fileSize\">Size {{ formatFileSize(record.fileSize) }}</span>"),
        ("{{ record.fileExists ? '文件在服务器' : '文件缺失' }}", "{{ record.fileExists ? 'File on server' : 'File missing' }}"),
        (">下载<", ">Download<"),
        (">安装<", ">Install<"),
        (">清理安装包<", ">Clean Package<"),
        (">删除记录<", ">Delete Record<"),
        ('暂无下载任务和记录', 'No download tasks or records'),
        ('完成后可在这里查看状态与操作', 'Completed tasks will appear here'),
        ("ElMessage.error(data.error || '加载记录失败')", "ElMessage.error(data.error || 'Failed to load records')"),
        ("ElMessage.error('加载记录失败')", "ElMessage.error('Failed to load records')"),
        ("await ElMessageBox.confirm('确定删除这条记录吗？', '确认删除', { type: 'warning' })", "await ElMessageBox.confirm('Are you sure you want to delete this record?', 'Confirm Delete', { type: 'warning' })"),
        ("if (!data.ok) throw new Error(data.error || '删除失败')", "if (!data.ok) throw new Error(data.error || 'Delete failed')"),
        ("ElMessage.success('记录已删除')", "ElMessage.success('Record deleted')"),
        ("ElMessage.error(error.message || '删除失败')", "ElMessage.error(error.message || 'Delete failed')"),
        ("await ElMessageBox.confirm('确定清空全部下载记录吗？', '确认清空', {", "await ElMessageBox.confirm('Are you sure you want to clear all download records?', 'Confirm Clear', {"),
        ("confirmButtonText: '清空'", "confirmButtonText: 'Clear'"),
        ("cancelButtonText: '取消'", "cancelButtonText: 'Cancel'"),
        ("if (!data.ok) throw new Error(data.error || '清空失败')", "if (!data.ok) throw new Error(data.error || 'Failed to clear records')"),
        ("ElMessage.success('记录已清空')", "ElMessage.success('Records cleared')"),
        ("ElMessage.error(error.message || '清空失败')", "ElMessage.error(error.message || 'Failed to clear records')"),
        ("confirmButtonText: '清理安装包'", "confirmButtonText: 'Clean Package'"),
        ("if (!data.ok) throw new Error(data.error || '清理失败')", "if (!data.ok) throw new Error(data.error || 'Cleanup failed')"),
        ("ElMessage.error(error.message || '清理失败')", "ElMessage.error(error.message || 'Cleanup failed')"),
        ("await ElMessageBox.confirm('确定清理服务器上的下载目录吗？', '确认清理', {", "await ElMessageBox.confirm('Are you sure you want to clean the server download directory?', 'Confirm Cleanup', {"),
        ("confirmButtonText: '清理'", "confirmButtonText: 'Clean'"),
        ("if (!data.ok) throw new Error(data.error || '清理失败')", "if (!data.ok) throw new Error(data.error || 'Cleanup failed')"),
        ("markTaskInterrupted(taskId, data?.error || '任务已不存在')", "markTaskInterrupted(taskId, data?.error || 'Task no longer exists')"),
        ("const markInterrupted = (message = '任务已失效，可能是服务重启或页面切换后丢失，请重新发起下载') =>", "const markInterrupted = (message = 'Task is no longer valid, possibly due to server restart or page navigation. Please re-initiate the download.') =>"),
        ("message = '任务已失效，可能是服务重启或页面切换后丢失，请重新发起下载'", "message = 'Task is no longer valid, possibly due to server restart or page navigation. Please re-initiate the download.'"),
        ("if (status === 'completed' || status === 'ready') return '已完成'", "if (status === 'completed' || status === 'ready') return 'Completed'"),
        ("if (status === 'failed' || status === 'error') return '失败'", "if (status === 'failed' || status === 'error') return 'Failed'"),
        ("return '进行中'", "return 'In Progress'"),
        ("if (!bytes) return '未知'", "if (!bytes) return 'Unknown'"),
        ("if (!value) return '未知时间'", "if (!value) return 'Unknown'"),
        ("return date.toLocaleString('zh-CN', {", "return date.toLocaleString(undefined, {"),
    ],
    'src/components/IpaManager.vue': [
        ('IPA 管理', 'IPA Manager'),
        ('管理服务器上的 IPA 文件 · 已占用 ', 'Manage IPA files on the server · Storage used: '),
        ('全选', 'Select All'),
        ("批量清理{{ selectedCount > 0 ? `（${selectedCount}）` : '' }}", "Batch Clean{{ selectedCount > 0 ? ` (${selectedCount})` : '' }}"),
        ("{{ uploading ? `上传中 ${uploadProgress}%` : '上传 IPA' }}", "{{ uploading ? `Uploading ${uploadProgress}%` : 'Upload IPA' }}"),
        ('>刷新<', '>Refresh<'),
        ("{{ item.artistName || '未知开发者' }}", "{{ item.artistName || 'Unknown Developer' }}"),
        ('版本 {{ item.version || ', "Version {{ item.version || '"),
        ("账号 {{ item.accountEmail || '未知账号' }}", "Account {{ item.accountEmail || 'Unknown Account' }}"),
        (">下载<", ">Download<"),
        (">安装<", ">Install<"),
        ("仅下载", "Download Only"),
        (">安装<", ">Install<"),
        (">删除<", ">Delete<"),
        ('暂无 IPA 文件', 'No IPA files found'),
        ('下载完成后会出现在这里', 'Files will appear here after download'),
        ("title=\"确认删除 IPA\"", "title=\"Confirm Delete IPA\""),
        ('确定删除这个 IPA 文件吗？', 'Are you sure you want to delete this IPA file?'),
        ('只删除服务器上的这个 IPA 文件，不清数据库。', 'This only deletes the IPA file from the server, not from the database.'),
        ('>\\n          取消\\n        <', '>\\n          Cancel\\n        <'),
        ('>\\n          删除\\n        <', '>\\n          Delete\\n        <'),
        ("await ElMessageBox.confirm(`确定批量清理 ${selectedIds.value.length} 个安装包吗？`, '确认批量清理', {", "await ElMessageBox.confirm(`Are you sure you want to batch clean ${selectedIds.value.length} package(s)?`, 'Confirm Batch Clean', {"),
        ("confirmButtonText: '批量清理'", "confirmButtonText: 'Batch Clean'"),
        ("cancelButtonText: '取消'", "cancelButtonText: 'Cancel'"),
        ("ElMessage.success(`已清理 ${selectedIds.value.length} 个安装包`)", "ElMessage.success(`Cleaned ${selectedIds.value.length} package(s)`)"),
        ("ElMessage.error(error.message || '批量清理失败')", "ElMessage.error(error.message || 'Batch clean failed')"),
        ("if (!data.ok) throw new Error(data.error || '加载失败')", "if (!data.ok) throw new Error(data.error || 'Failed to load')"),
        ("ElMessage.error(error.message || '加载失败')", "ElMessage.error(error.message || 'Failed to load')"),
        ("if (data.ok) return { missing: false }", "if (data.ok) return { missing: false }"),
        ("if (response.status === 404 || data.error === 'IPA 文件不存在') {", "if (response.status === 404 || data.error === 'IPA file does not exist') {"),
        ("throw new Error(data.error || '删除失败')", "throw new Error(data.error || 'Delete failed')"),
        ("ElMessage.warning('文件已不存在，列表已刷新')", "ElMessage.warning('File no longer exists, list refreshed')"),
        ("ElMessage.success('IPA 已删除')", "ElMessage.success('IPA deleted')"),
        ("ElMessage.error(error.message || '删除失败')", "ElMessage.error(error.message || 'Delete failed')"),
        ("if (!bytes) return '未知'", "if (!bytes) return 'Unknown'"),
        ("if (!value) return '未知时间'", "if (!value) return 'Unknown'"),
        ("return date.toLocaleString('zh-CN', {", "return date.toLocaleString(undefined, {"),
        ("ElMessage.error('只能上传 .ipa 格式的文件')", "ElMessage.error('Only .ipa files can be uploaded')"),
        ("ElMessage.error('上传文件大小不能超过 2GB')", "ElMessage.error('File size cannot exceed 2GB')"),
        ("ElMessage.success('文件上传成功')", "ElMessage.success('File uploaded successfully')"),
        ("ElMessage.error(response.error || '上传失败')", "ElMessage.error(response.error || 'Upload failed')"),
        ("ElMessage.error('上传失败：' + error.message)", "ElMessage.error('Upload failed: ' + error.message)"),
    ],
    'src/components/Settings.vue': [
        ('账号安全', 'Account Security'),
        ('修改管理员登录凭据', 'Change Admin Login Credentials'),
        ("{{ appStore.authState.user?.username || '未知' }}", "{{ appStore.authState.user?.username || 'Unknown' }}"),
        ('管理员账号', 'Admin Account'),
        ('>\\n            修改账号\\n          <', '>\\n            Edit Account\\n          <'),
        ("title=\"修改登录凭据\"", "title=\"Change Login Credentials\""),
        ('label="当前密码"', 'label="Current Password"'),
        ('placeholder="请输入当前密码"', 'placeholder="Please enter current password"'),
        ('label="新用户名（留空则不修改）"', 'label="New Username (leave blank to keep current)"'),
        ('placeholder="输入新用户名或留空"', 'placeholder="Enter new username or leave blank"'),
        ('label="新密码"', 'label="New Password"'),
        ('placeholder="请输入新密码"', 'placeholder="Please enter new password"'),
        ('label="确认新密码"', 'label="Confirm New Password"'),
        ('placeholder="请再次输入新密码"', 'placeholder="Please confirm new password"'),
        ('>\\n            取消\\n          <', '>\\n            Cancel\\n          <'),
        ('>\\n            确认修改\\n          <', '>\\n            Confirm Changes\\n          <'),
        ('通知管理', 'Notification Settings'),
        ('自定义浏览器通知行为', 'Configure browser notification behavior'),
        ('浏览器通知未授权', 'Browser notifications not authorized'),
        ('需要授权后才能接收通知', 'Authorization required to receive notifications'),
        ('>\\n            开启权限\\n          <', '>\\n            Enable Permission\\n          <'),
        ('✅ 浏览器通知已授权', '✅ Browser notifications authorized'),
        ('新版本检测', 'New Version Detection'),
        ('订阅应用有更新时通知', 'Notify when subscribed apps have updates'),
        ('下载完成', 'Download Complete'),
        ('IPA 下载成功时通知', 'Notify when IPA download succeeds'),
        ('下载失败', 'Download Failed'),
        ('IPA 下载出错时通知', 'Notify when IPA download fails'),
        ('版本信息', 'Version Info'),
        ('当前前端构建版本', 'Current frontend build version'),
        ('版本号', 'Version Number'),
        ("message: '请输入当前密码'", "message: 'Please enter current password'"),
        ("message: '请输入新密码'", "message: 'Please enter new password'"),
        ("message: '请确认新密码'", "message: 'Please confirm new password'"),
        ("callback(new Error('两次输入的密码不一致'))", "callback(new Error('Passwords do not match'))"),
        ("ElMessage.success('通知权限已开启')", "ElMessage.success('Notification permission granted')"),
        ("ElMessage.warning('通知权限被拒绝，可在浏览器设置中手动开启')", "ElMessage.warning('Notification permission denied, you can enable it in browser settings')"),
        ("let msg = '修改失败'", "let msg = 'Change failed'"),
        ("ElMessage.success('登录凭据已修改，请重新登录')", "ElMessage.success('Login credentials updated, please log in again')"),
        ("ElMessage.error(e?.message || '修改失败')", "ElMessage.error(e?.message || 'Change failed')"),
    ],
    'src/stores/app.js': [
        ('// 下载任务状态', '// Download task state'),
        ('// 下载任务队列', '// Download task queue'),
        ('// 批量下载草稿项', '// Batch download draft items'),
        ('// 当前激活的页面标签', '// Currently active tab'),
        ('// 账号更新计数器', '// Account update counter'),
        ('// 管理员登录态', '// Admin login state'),
        ("let msg = '登录失败'", "let msg = 'Login failed'"),
        ('// 设置选中的应用', '// Set selected app'),
        ('// 更新下载状态', '// Update download state'),
        ('// 添加任务到队列', '// Add task to queue'),
        ('// 更新现有任务', '// Update existing task'),
        ('// 添加新任务', '// Add new task'),
        ('// 更新队列任务', '// Update queue task'),
        ('// 从队列移除任务', '// Remove task from queue'),
        ('// 清空任务队列', '// Clear task queue'),
        ('// 添加批量下载草稿项', '// Add batch download draft item'),
        ('// 触发账号更新', '// Trigger account update'),
    ],
    'src/composables/useNotifications.js': [
        ('`🔄 ${update.app_name} 有新版本`', '`🔄 ${update.app_name} has a new version`'),
        ("send(\n    `✅ 下载完成`,", "send(\n    `✅ Download Complete`,"),
        ("send(\n    `❌ 下载失败`,", "send(\n    `❌ Download Failed`,"),
        ("send(\n    `🔄 发现新版本`,", "send(\n    `🔄 New Version Found`,"),
        ("send(\n        `🔄 ${update.app_name} 有新版本`,", "send(\n        `🔄 ${update.app_name} has a new version`,"),
    ],
}

# Also handle AccountManager.vue and DownloadManager.vue with sed/file read
import os

base = '/home/runner/work/ipaTool/ipaTool'

for rel_path, replacements in files.items():
    filepath = os.path.join(base, rel_path)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for old, new in replacements:
        content = content.replace(old, new)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f'Updated: {rel_path}')
    else:
        print(f'No changes: {rel_path}')

print('Done')
